Init Account by tying it to near
bafnetwork/baf-wallet-v3 pull request #32
Opened 2021-06-25 13:44 UTC by Lev-Stambler

- Add functionality which ties a user's Discord keys with their Near Account
- Add functionality to remove Discord keys from Near Account

In a future PR we gotta talk about a UX to go along with this, see #31

2021-06-25 23:33 UTC, Sladuca requested changes
This is way simpler! Gonna be even simpler with one contract!

See comments

2021-06-25 23:33 UTC, Sladuca commented on libs/near/src/web/wallet-connect.ts
> +  console.log(near);
console log

2021-06-25 23:33 UTC, Sladuca commented on libs/near/src/web/wallet-connect.ts
> +  const wallet = new WalletConnection(near, 'Baf wallet?');
why question mark?

2021-06-27 20:04 UTC, Lev-Stambler commented on libs/near/src/web/wallet-connect.ts
> +  const wallet = new WalletConnection(near, 'Baf wallet?');
??? lmao my b

2021-06-27 20:05 UTC, Lev-Stambler commented on apps/frontend/src/config/init.svelte
> +  export async function initApp(): Promise<{ initNear: boolean }> {
My bad, I will make sure to not do that in future

2021-06-27 20:25 UTC, Sladuca requested changes
Address other changes, or at least comment why you disagree

2021-06-27 20:25 UTC, Sladuca commented on apps/frontend/src/state/accounts.svelte
> +    keys: KeyState | null;
please move inline interface decl into a separate named interface

2021-06-27 20:25 UTC, Sladuca commented on apps/frontend/src/state/chains.svelte
> +    console.log(associatedKeys);
add comment if you have a good reason for these to stay

2021-06-27 20:25 UTC, Sladuca commented on libs/interfaces/src/lib/chains.ts
> +  associatedKeys: <T>(account: Account) => Promise<PublicKey<T>[]>;
see this

2021-06-27 22:03 UTC, Lev-Stambler commented
@Sladuca what do you mean by `see this`?

2021-06-28 12:32 UTC, Sladuca approved these changes
I'll fix the rest of the things, dw about it

2021-06-28 12:34 UTC, merged